# Hotel Domain - Multi-task Approach Configuration

# Inherit from base config
defaults:
  - base_config

# Override specific settings
model:
  approach: "multitask"  # multitask vs multibranch
  domain: "hotel"
  num_aspect_categories: 34
  
# Hotel-specific aspect categories
aspect_categories:
  - "FACILITIES#CLEANLINESS"
  - "FACILITIES#COMFORT"
  - "FACILITIES#DESIGN&FEATURES"
  - "FACILITIES#GENERAL"
  - "FACILITIES#MISCELLANEOUS"
  - "FACILITIES#PRICES"
  - "FACILITIES#QUALITY"
  - "FOOD&DRINKS#MISCELLANEOUS"
  - "FOOD&DRINKS#PRICES"
  - "FOOD&DRINKS#QUALITY"
  - "FOOD&DRINKS#STYLE&OPTIONS"
  - "HOTEL#CLEANLINESS"
  - "HOTEL#COMFORT"
  - "HOTEL#DESIGN&FEATURES"
  - "HOTEL#GENERAL"
  - "HOTEL#MISCELLANEOUS"
  - "HOTEL#PRICES"
  - "HOTEL#QUALITY"
  - "LOCATION#GENERAL"
  - "ROOMS#CLEANLINESS"
  - "ROOMS#COMFORT"
  - "ROOMS#DESIGN&FEATURES"
  - "ROOMS#GENERAL"
  - "ROOMS#MISCELLANEOUS"
  - "ROOMS#PRICES"
  - "ROOMS#QUALITY"
  - "ROOM_AMENITIES#CLEANLINESS"
  - "ROOM_AMENITIES#COMFORT"
  - "ROOM_AMENITIES#DESIGN&FEATURES"
  - "ROOM_AMENITIES#GENERAL"
  - "ROOM_AMENITIES#MISCELLANEOUS"
  - "ROOM_AMENITIES#PRICES"
  - "ROOM_AMENITIES#QUALITY"
  - "SERVICE#GENERAL"
# Data paths
data:
  data_dir: "data/datasets/vlsp2018_hotel"
  domain: "hotel"
  train_path: "data/datasets/vlsp2018_hotel/1-VLSP2018-SA-Hotel-train.txt"
  val_path: "data/datasets/vlsp2018_hotel/2-VLSP2018-SA-Hotel-dev.txt"
  test_path: "data/datasets/vlsp2018_hotel/3-VLSP2018-SA-Hotel-test.txt"

# Training specific to Hotel domain
training:
  batch_size: 25  # As used in original paper
  
# Output settings
output:
  model_name: "hotel_multitask"
  save_dir: "models/hotel_multitask"
  results_dir: "results/hotel_multitask" 